reactjs/ar.react.dev

gatsby-config.js

fix try it on CodePen

---

src/components/Layout/Layout.js
src/components/LayoutFooter/Footer.js
src/components/LayoutHeader/DocSearch.js
src/components/LayoutHeader/Header.js
src/html.js
src/pages/index.js
yarn.lock

- There is no need to add multiple `dir="rtl"` attributes in multiple places, it's enough to have it set on `<body>` or `<html>`
- changed the `html` `lang` to be `ar`
Also `yarn.lock` was not up to date so I fixed it in the PR too.

Change document language & set the dir attribute once

---

CONTRIBUTING.md

Contributors should be able to immediately know that we're using Hsoub's translation in this first phase, per the discussion in #24.

Let contributors know we're using Hsoub's translation

---

README.md

Adding contribution steps to readme

---

.gitignore
content/docs/lists-and-keys.md

Done Translating-lists-and-keys.md

---

content/docs/lifting-state-up.md

Reserving the file "lifting-state-up.md" for translation.

Translating 'lifting-state-up.md'

---

content/community/nav.yml
content/docs/nav.yml
src/components/LayoutFooter/Footer.js

Translate footer

---

content/docs/context.md

Done Translating-context.md

---

content/docs/error-boundaries.md

Error Boundaries Page

---

content/docs/reference-react-component.md

Done Translating-reference-react-component.md

---

content/docs/typechecking-with-proptypes.md

Finalize Translating typechecking-with-proptypes.md

[DONE] typechecking-with-proptypes.md translation

---

content/docs/typechecking-with-proptypes.md

I just start translating the **typechecking with proptypes** page so please attach it to me in the TodoList .
Thanks .

Start Translating typechecking-with-proptypes.md

---

content/docs/faq-styling.md

[Done] Translating FAQ reference to faq-styling.md

---

content/docs/faq-state.md

[Done] Translation of FAQ reference to faq-state.md

---

content/docs/faq-structure.md

[Done] translating faq-structure.md

---

content/docs/reference-dom-elements.md
content/docs/reference-events.md

Translating reference events.md

---

content/docs/static-type-checking.md

[Done] Translation of static-type-checking.md 

---

content/docs/nav.yml
content/docs/optimizing-performance.md

~~:construction:  Work in progress ...~~
Done

[Done] Start translating "Optimizing Performance"

---

content/docs/nav.yml
content/docs/reconciliation.md

~~:construction:  Work in progress ..~~ Done

[Done] Translate "Reconciliation"

---

content/docs/portals.md

[Done] Translation of portals.md ..

---

content/docs/integrating-with-other-libraries.md

[Done] Translation of intergrating-with-other-libraries.md ..

---

content/docs/nav.yml
content/docs/render-props.md

[Done] Translating Render props

---

content/community/support.md

[Done] translate community/support (related to #117)

---

src/components/LayoutHeader/DocSearch.js

I'm still looking for solutions to override Algolia templates, for "no results" message.
Or if it's fine like that let's merge it :)

add "react_ar" algolia app, resolves #106

---

content/community/articles.md

[Done] Translation of articles.md ..

---

content/community/external-resources.md

[Done] Translation of external-resources.md ..

---

plugins/gatsby-remark-header-custom-ids/gatsby-ssr.js

Fixed Anchors position for RTL, preview below:

[Done] Anchors Position - RTL Support

---

content/community/conferences.md

[Done] Translation of conferences.md ..

---

content/community/videos.md

I don't know if should translate the titles or leave them like conf section.

[Done] Translation of videos.md ..

---

content/community/tools-model-mgmt.md

[DONE] Translation of tools-model-mgmt.md ..

---

content/community/podcasts.md

[Done] Translation of podcasts.md ..

---

content/community/tools-misc.md

translate file : `content/community/tools-misc.md`
Ref : [here ](https://github.com/reactjs/ar.reactjs.org/issues/117#issuecomment-518014608)

[Done] Tools misc

---

content/home/examples/a-simple-component.js

Why not translate the test inside the components?

Translate text in `a-simple-component.js` file

---

content/community/tools-ui-components.md

<div dir='rtl'> 
الرجاء مراجعة هذا الطلب بكل دقة بحكم انشغالي في المدة الاخيرة لم اتمكن من تدقيق في اختيار كلمات الترجمة .. 
لذالك ان كانت هناك تعبير افضل او تصحيح لبعض العبارات لا تتردد في ذالك و شكرا لكم .. 
</div>

[DONE] Translation of tools-ui-components.md ..

---

src/pages/404.js

[DONE] Translation 404.js content ..

---

src/pages/blog/all.html.js

[DONE] Translation blog/all.js content ..

---

src/templates/components/NavigationFooter/NavigationFooter.js

[DONE] Fix Navigation footer for arabic content .. 

---

src/pages/jsx-compiler.html.js

[DONE] Translation of jsxCompiler.js content ..

---

content/docs/nav.yml

[DONE] Fix nav docs --21/09/2019 ..

---

content/docs/introducing-jsx.md

Format & fix typos

---

content/docs/add-react-to-a-website.md

<div dir="rtl">إصلاح بعض اﻷخطاء اﻹملائية وعلامات الترقيم، واقتراح تعديلات في صياغة بعض الجمل.</div>

Fix typos & propose changes

---

content/docs/error-boundaries.md

Review translation & clean-up

---

content/community/meetups.md

[Done] Translation of meetups.md v2 .. 

---

content/docs/cdn-links.md

Fix typos & review translation

---

content/docs/nav.yml

<!--
Thank you for the PR! Contributors like you keep React awesome!
Please see the Contribution Guide for guidelines:
https://github.com/reactjs/reactjs.org/blob/master/CONTRIBUTING.md
If your PR references an existing issue, please add the issue number below

[DONE] Update docs navigation names

---

content/docs/faq-ajax.md

Fix typos & improve the translation

Fix typos & improve the translation

---

yarn.lock

Note to Hacktoberfest 🎃 participants:
While we appreciate the enthusiasm, we are experiencing a high volume of drive-by pull requests (one-line changes, README tweaks, etc.). Please remember that hundreds of people are subscribed to this repo and will receive notifications for these PRs. Spam submissions will be closed and won't count towards your Hacktoberfest goals.
Please search for issues tagged [`good first issue`][gfi] or [`hacktoberfest`][hacktoberfest] to find things to work on.
You can also search [all of GitHub][all].
[gfi]: https://github.com/reactjs/reactjs.org/issues?q=is%3Aissue+is%3Aopen+label%3A"good+first+issue"
[hacktoberfest]: https://github.com/reactjs/reactjs.org/issues?q=is%3Aissue+is%3Aopen+label%3A"good+first+issue"
[all]: …

patch: fix deps

---

content/docs/error-decoder.md

Translating " Docs/error-decoder " to Arabic.

---

content/blog/2021-06-08-the-plan-for-react-18.md
content/docs/how-to-contribute.md

[WIP] translate branch_organization & feature_flags

---

src/content/blog/2024/04/25/react-19-upgrade-guide.md
src/content/community/conferences.md
src/content/learn/installation.md
src/content/reference/react-dom/components/script.md
src/content/reference/react-dom/preinit.md
src/content/reference/react/act.md
src/content/reference/react/cache.md

- **Update to CodePen URL (https://github.com/reactjs/react.dev/pull/6452)**
- **Remove mention of Suspensey `<script />` (https://github.com/reactjs/react.dev/pull/6945)**
- **Small typo - Update cache.md (https://github.com/reactjs/react.dev/pull/6935)**
- **Update preinit.md 📜 (https://github.com/reactjs/react.dev/pull/6938)**
- **docs(api-act): api act parts word error (https://github.com/reactjs/react.dev/pull/6939)**
- **Recommend installing exact RC (https://github.com/reactjs/react.dev/pull/6944)**
- **rearrange conferences (https://github.com/reactjs/react.dev/pull/6952)**

Sync with react.dev June 17th
