reactjs/ar.react.dev

src/components/LayoutHeader/DocSearch.js
src/components/LayoutHeader/Header.js

By merging this PR, and #36 #37 #38 the Home page become entirely translated  🎉

Translate  Header

---

src/pages/index.js

Translate Home Page banner and page title

---

.gitignore
content/docs/addons-shallow-renderer.md

Done Translating-addons-shallow-renderer.md

---

content/docs/reference-test-renderer.md

Done Translating-reference-test-renderer.md

---

content/docs/create-a-new-react-app.md

#1 translating create-new-react-app page

Translating create-a-new-react-app.md

---

content/docs/reference-react-dom-server.md

Done Translating-reference-react-dom-server.md

---

content/docs/fragments.md

Done Translating-fragments.md

---

content/docs/nav.yml
content/docs/react-without-jsx.md
content/docs/reference-react.md
package.json

[Done] React without JSX

---

content/docs/faq-ajax.md

[DONE] Translate AJAX and APIs FAQ Page reference to faq-ajax.md

---

content/docs/react-without-es6.md

working on the page: "React without ES6"

Translating - React without ES6

---

content/docs/reference-javascript-environment-requirements.md

Translating reference-javascript-environment-requirements.md

---

src/components/CodeEditor/CodeEditor.js
src/components/CodeExample/CodeExample.js
src/components/ErrorDecoder/ErrorDecoder.js
src/components/LayoutHeader/Header.js
src/components/LayoutHeader/SearchSvg.js

[Done] translate components

---

content/warnings/dont-call-proptypes.md

I haven't translated the `title` because I wasn't sure whether to do so or not since some of the translations did and some others didn't!

translated warnings/dont-call-proptypes

---

content/community/tools-debugging.md

[Done] Translation of debugging.md  ..

---

content/docs/faq-versioning.md

[Done] translating versioning

---

content/tutorial/nav.yml

[Done] Translation of tutorial/nav.yml ..

---

content/docs/faq-build.md

[Done] Translation of faq-build.md ..

---

content/community/tools-data-fetching.md

If there is a better expression than ` التطبيقات المبنية على البيانات` to translate the `data-driven app` .. just suggest  ...

[Done] Translation of data-fetching.md ..

---

content/community/nav.yml

hi everyone ! 
translate file `content/community/nav.yml`

[DONE] Update content/community/nav.yml

---

content/community/courses.md

@moast , thank you for your contribution ...
The next time , please create a Pull Request. If you don't know how to do this follow this [video](https://www.youtube.com/watch?v=l5NrYIa_aG4) ..

[Done] Translation courses.md - @Moast

---

content/community/tools-comp-workbenches.md

[DONE] Translation of tools-comp-workbenches.md to ar ..

---

content/community/nav.yml
content/community/tools-routing.md

[DONE] Translation of tools-routing.md .. 

---

content/community/tools-jsx.md

translate file : `content/community/tools-jsx.md`
Ref : [here ](https://github.com/reactjs/ar.reactjs.org/issues/117#issuecomment-517815828)

[DONE] Update tools-jsx.md

---

src/pages/versions.js

 [DONE] Translation of react versions content ..

---

src/templates/codepen-example.js

[DONE] Translation codepen-example.js content ..

---

src/content/learn/add-react-to-an-existing-project.md
src/sidebarLearn.json

[DONE] Translate `Add React to an existing project`

---

src/content/reference/react/useId.md

useId page translation

---

src/content/reference/react/useDebugValue.md

[Done] Translating `useDebugValue`

---

.github/workflows/analyze_comment.yml
src/content/reference/react-dom/index.md

- add condition to just when branch is not equal to main
- test: add condition
- revert
- reference/react-dom/index

Translating: Reference/react-dom/index

---

.github/workflows/analyze_comment.yml
src/content/reference/react/components.md
src/sidebarReference.json

- add condition to just when branch is not equal to main
- test: add condition
- revert
- translate components
- sidebar

Translating Reference: React/Components

---

src/content/learn/describing-the-ui.md

The current translation of this index page is not coherent with the translations done in the sub-pages in this section. Also the sentences in the code block including images' alt is not translated.
Changes made:
- Make the translation of this page coherent
- Translate sentences in the code blocks

Make `Describing the UI` coherent with translations made in the sub-pages of this section
